### ISSUE TITLE
rozkład zmian miesięcznych i kwartalnych w wybranych przez użytkownika parach walutowych

### ISSUE THREAD

**Issue by snsv-dy** [IIS-ZPI/ZPI2020_IO1_Codesalmon#46]
Fragment dokumentu wymagań:
> rozkład zmian miesięcznych i kwartalnych w dowolnych wybranych przez użytkownika parach
walutowych np. EUR/USD. Analiza polega na wyliczeniu w kolejnym dniu sesji zmiany
w stosunku do sesji poprzedniej.

Story Points: 5

**Comment by klima7** [comment]
Do tego issue bardziej pasuje feature niż enhancement.
