### ISSUE TITLE
Wyświetlanie zapisywanie wyniku

### ISSUE THREAD

**Issue by snsv-dy** [IIS-ZPI/ZPI2020_IO1_Codesalmon#47]
Należy dodać do aplikacji funkcjonalność informowania użytkownika o wynikach jej działania. Możliwymi rozwiązaniami jest wyświetlanie wyniku w konsoli, zapisywanie danych w pliku tekstowym, w pliku CSV lub innym formacie pliku.

Story Points: 4

**Comment by klima7** [comment]
Do tego issue bardziej pasuje feature niż enhancement.
